[[redirects]]
  from = "/.well-known/apple-app-site-association"
  to = "/apple-app-site-association.json"
  status = 200
  force = true


# [[redirects]]
#  from = "/"
#  to = "https://www.widget.vision/"
#  status = 302
#  force = true


[[redirects]]
  from = "/list"
  to = "https://www.widget.vision/list"
  status = 302
  force = true

[[redirects]]
  from = "/x/*"
  to = "https://transparent.vision/:splat"
  status = 302
  force = true
  
[[edge_functions]]
  path = "/*"
  excludedPath = ["/widgets/*", "/.well-known/*", "/apple-app-site-association.json"]
  function = "metadata"