[[redirects]]
  from = "/.well-known/apple-app-site-association"
  to = "/apple-app-site-association.json"
  status = 200
  force = true

[[redirects]]
  from = "/"
  to = "https://www.widget.vision/"
  status = 301
  force = true

[[edge_functions]]
  path = "/*"
  function = "metadata"