[[redirects]]
  from = "/.well-known/apple-app-site-association"
  to = "/apple-app-site-association.json"
  status = 200
  force = true

[[redirects]]
  from = "/"
  to = "https://www.widget.vision/"
  status = 301
  force = true

[[redirects]]
  from = "/x/*"
  to = "https://www.widget.vision/:splat"
  status = 301
  force = true
  
[[edge_functions]]
  path = "/*"
  excludedPath = ["/.well-known/*", "/apple-app-site-association.json"]
  function = "metadata"