[[redirects]]
  from = "/.well-known/apple-app-site-association"
  to = "/apple-app-site-association.json"
  status = 200
  force = true


# [[redirects]]
#  from = "/"
#  to = "https://www.widget.vision/"
#  status = 302
#  force = true

[[redirects]]
  from = "/list"
  to = "https://translucent.directory"
  status = 302
  force = true
  
[[edge_functions]]
  path = "/*"
  excludedPath = ["/list", "/widgets/*", "/.well-known/*", "/apple-app-site-association.json"]
  function = "metadata"